// src/routes/(auth)/forgot-password/+page.svelte
<script>
  import { Button } from "$lib/components/forms/button";
  import { Input } from "$lib/components/forms/input";
</script>

<form action="#">
  <h1 class="text-2xl font-bold mb-4 text-white">
    Forgot your password?
  </h1>

  <div class="mb-3">
    <Input props={{
      type: "email",
      placeholder: "john@company.com",
      size: "large",
      label: "Your email to reset your password",
    }} />
  </div>

  <div class="mt-3 flex items-start">
    <Button props={{ type: "submit", variant: "blue", size: "lg", disabled: false, full: true }}>
      Send reset link
    </Button>
  </div>
</form>

<div>
  <p class="mt-2 text-sm text-gray-400">
    You remember your password? <a href="/login" class="text-blue-600 hover:text-blue-500 hover:underline">Sign in</a>
  </p>
</div>

// src/app/(auth)/forgot-password/page.tsx
/* eslint-disable @typescript-eslint/no-misused-promises */
"use client";

import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/lib/components/ui/card";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/lib/components/ui/button";
import { Input } from "@/lib/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/lib/components/ui/form";
import { Outfit } from "next/font/google";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { cn } from "@/lib/utils";
import Link from "next/link";

const outfit = Outfit({ subsets: ["latin"] });

const ForgotPassword = (): JSX.Element => {
  const formSchema = z.object({
    email: z.string().email({
      message: "Your email is invalid."
    }).nonempty({
      message: "Your email is required."
    })
  });

  const form = useForm({
    resolver: zodResolver(formSchema)
  });

  const onSubmit = (): void => {
    console.log("Submitted!");
  };

  return (
    <div className="flex flex-col items-center justify-center mt-10 md:mt-16 px-3">
      <Card className="w-full max-w-[30rem]">
        <CardHeader className="-mb-3">
          <CardTitle className={outfit.className}>Forgot your password?</CardTitle>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-2">
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email</FormLabel>
                    <FormControl>
                      <Input type="email" placeholder="john@company.com" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <Button type="submit" className={cn("w-full flex gap-1", outfit.className)}>
                Send reset link
              </Button>
            </form>
          </Form>
        </CardContent>

        <CardFooter className="flex flex-col justify-start items-start">
          <div>
            Remember your password?&nbsp;<Link href={"/sign-in"} className="text-primary hover:underline">Click here to sign in.</Link>
          </div>
        </CardFooter>
      </Card>
    </div>
  );
};

export default ForgotPassword;
