// src/routes/(auth)/sign-in/+page.svelte
<script lang="ts">
  import { Button } from "$lib/components/button";
  import { Input } from "$lib/components/forms/input";
  import { Container } from "$lib/components/layout/container";

  export let email: string;
  export let password: string;
</script>

<Container maxSize="md">
  <form action="?/login" method="POST">
    <div class="mb-3">
      <Input bind:value={email} props={{ type: "text", label: "Email address", placeholder: "johndoe@example.com", width: "full", size: "small", name: "email" }} />
    </div>

    <div class="mb-0">
      <Input bind:value={password} props={{ type: "password", label: "Password", placeholder: "••••••••", width: "full", size: "small", name: "password" }} />
    </div>

    <div class="mt-5">
      <Button props={{ type: "submit", size: "large", variant: "blue" }}>
        Se connecter
      </Button>
    </div>

    <div class="mt-4">
      <p class="text-sm font-sm text-gray-400">
        Don't have an account? <a href="/sign-up" class="hover:text-gray-300 transition-all ease-in-out 2s">Sign up</a>
      </p>
    </div>
  </form>
</Container>

// src/app/(auth)/sign-in/page.tsx
"use client";

import { Button } from "#/lib/components/atoms/button";
import { Card } from "#/lib/components/atoms/card";
import { Input } from "#/lib/components/atoms/input";
import { Text } from "#/lib/components/atoms/text";
import Link from "next/link";
import type { ReactElement } from "react";

const SignInPage = (): ReactElement => {
  return (
    <>
      <Card size="sm">
        <div className="p-0">
          <h1 className="mb-1 text-xl font-bold text-white md:text-2xl">Connect to your account</h1>
        </div>

        <div className="flex flex-col mt-2">
          <Input
            label="Email address"
            placeholder="john@company.com"
            type="email"
            className="mb-2"
          />

          <Input
            label="Password"
            placeholder="••••••••"
            type="password"
            className="mb-2.5"
          />

          <Button className="mt-2">Sign in</Button>

          <div className="flex flex-col mt-4">
            <Text className="text-gray-400">
              Don&apos;t have an account? <Link className="text-blue-600 hover:text-blue-500" href="/sign-up">Sign up</Link>
            </Text>

            <Text className="text-gray-400">
              Forgot your password? <Link className="text-blue-600 hover:text-blue-500" href="/reset-password">Reset it</Link>
            </Text>
          </div>
        </div>
      </Card>
    </>
  );
};

export default SignInPage;
