// src/app/(auth)/sign-up/page.tsx
"use client";

import { Button } from "#/lib/components/atoms/button";
import { Card } from "#/lib/components/atoms/card";
import { Checkbox } from "#/lib/components/atoms/checkbox/checkbox";
import { Input } from "#/lib/components/atoms/input";
import { Text } from "#/lib/components/atoms/text";
import Link from "next/link";
import type { ReactElement } from "react";

const SignInPage = (): ReactElement => {
  return (
    <>
      <Card size="sm">
        <div className="p-0">
          <h1 className="mb-1 text-xl font-bold text-white md:text-2xl">Connect to your account</h1>
        </div>

        <div className="flex flex-col mt-2">
          <Input
            label="Email address"
            placeholder="john@company.com"
            type="email"
            className="mb-2"
          />

          <Input
            label="Password"
            placeholder="••••••••"
            type="password"
            className="mb-2.5"
          />

          <Input
            label="Confirm password"
            placeholder="••••••••"
            type="password"
            className="mb-2.5"
          />

          <Checkbox>
            I agree to the <Link className="text-blue-600 hover:text-blue-500" href="/terms-of-service">Terms of Service</Link>
          </Checkbox>

          <Button className="mt-2">Let&apos;s go</Button>

          <div className="flex flex-col mt-4">
            <Text className="text-gray-400">
            Already have an account ? <Link className="text-blue-600 hover:text-blue-500" href="/sign-in">Sign in</Link>
            </Text>
          </div>
        </div>
      </Card>
    </>
  );
};

export default SignInPage;

// src/routes/(auth)/sign-up/+page.svelte
<script lang="ts">
  import { Button } from "$lib/components/button";
  import { Input, InputGroup } from "$lib/components/forms/input";
  import { Container } from "$lib/components/layout/container";
  import { PasswordForce } from "$lib/components/layout/password-force";

  export let email: string;
  export let password: string;
  export let passwordConfirm: string;
</script>

<Container maxSize="md">
  <form method="POST" action="?/register">
    <div class="mb-3">
      <Input bind:value={email} props={{ type: "email", label: "Email address", placeholder: "johndoe@example.com", width: "full", size: "small", name: "email" }} />
    </div>

    <div class="mb-2">
      <Input bind:value={password} props={{ label: "Password", type: "password", placeholder: "••••••••", width: "full", size: "small", name: "password" }} />
    </div>

    <div class="mb-3">
      <Input bind:value={passwordConfirm} props={{ label: "Confirm your password", type: "password", placeholder: "••••••••", width: "full", size: "small" }} />
    </div>

    <PasswordForce bind:password={password} />

    <div class="mt-5">
      <Button props={{ type: "submit", size: "large", variant: "blue" }}>
        S'inscrire
      </Button>
    </div>

    <div class="mt-4">
      <p class="text-sm font-sm text-gray-400">
        Already have an account? <a href="/sign-in" class="hover:text-gray-300 transition-all ease-in-out 2s">Log in</a>
      </p>
    </div>
  </form>
</Container>
