// src/lib/components/input/input.svelte
<script lang="ts">
  import clsx from "clsx";

  export let type: "url" | "text" = "url";
  export let disabled: boolean = false;
  export let size: "large" | "default" = "default";
  export let placeholder: string = "";
  export let id: string = "";
  export let value: string;

  if (id === "") id = Math.random().toString(36).substring(7);

  const sizeClass = clsx({"w-full": size === "large", "": size === "default"});

  const byDisabled = clsx({
    "outline-none focus:ring-1 bg-gray-700 border-gray-600 placeholder-gray-400 focus:ring-blue-500 focus:border-blue-500": disabled == false,
    "bg-gray-800 border-gray-700 placeholder-gray-500": disabled == true,
  });

  function changeValue(event: Event) {
    const target = event.target as HTMLInputElement;
    value = target.value;
  }
</script>

<input type={type} disabled={disabled} id={id} class="border sm:text-sm rounded-lg block p-2.5 text-white {sizeClass} {byDisabled}" placeholder={placeholder} on:input={changeValue}>

// src/lib/components/atoms/input/input.tsx
import type { Component } from "#/lib/utils/component";
import type { InputProps } from "./input.type";
import clsx from "clsx";

export const Input: Component<InputProps> = ({ type, name, placeholder, disabled, className, ...props }) => {
  return (
    <input
      className={clsx(
        "border",
        "rounded-lg block p-2.5 border-gray-600  placeholder-gray-400 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500",
        "border-gray-600 bg-gray-700 placeholder-gray-400 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500",
        {
          "text-white bg-gray-700": !disabled,
          "text-gray-400 bg-gray-700 cursor-not-allowed": disabled
        },
        className
      )}
      type={type}
      name={name}
      placeholder={placeholder}
      disabled={disabled}
      {...props}
    />
  );
};
