// src/lib/components/button/button.svelte
<script lang="ts">
  import clsx from "clsx";
  import type { ButtonProps } from ".";

  export let ButtonProps: ButtonProps;

  const sizeClass = clsx({
    "px-3 py-2 text-xs": ButtonProps.size === "small",
    "px-5 py-2.5 text-sm": ButtonProps.size === "default",
    "w-full px-5 py-2.5": ButtonProps.size === "large"
  });

  let colorClass = clsx({
    "bg-blue-600 hover:bg-blue-700 focus:ring-blue-800": ButtonProps.variant === "blue",
    "bg-red-700 hover:bg-red-800 focus:ring-red-800": ButtonProps.variant === "red",
    "bg-green-600 hover:bg-green-700 focus:ring-green-800": ButtonProps.variant === "green",
    "bg-yellow-600 hover:bg-yellow-700 focus:ring-yellow-800": ButtonProps.variant === "yellow",
    "bg-pro hover:bg-pro-h focus:ring-pro-f": ButtonProps.variant === "pro"
  });

  let colorClassDisabled = clsx({
    "bg-blue-800": ButtonProps.variant === "blue",
    "bg-red-500": ButtonProps.variant === "red",
    "bg-green-400": ButtonProps.variant === "green",
    "bg-yellow-400": ButtonProps.variant === "yellow",
    "bg-pro-d": ButtonProps.variant === "pro"
  });
</script>

<button on:click disabled={ButtonProps.disabled} class="{sizeClass} {ButtonProps.disabled ? colorClassDisabled : colorClass} text-white focus:ring-2 outline-none font-medium rounded-lg text-center transition-all ease-in-out 3s {ButtonProps.hidden ? 'hidden' : ''}">
  <slot></slot>
</button>

// src/lib/components/atoms/button/button.tsx
import type { Component } from "#/lib/utils/component";
import type { ButtonProps } from "./button.type";
import clsx from "clsx";

export const Button: Component<ButtonProps> = ({ children, variant, className, fulled, disabled, ...props }) => {
  return (
    <button
      className={clsx(
        "flex items-center justify-center px-4 py-2 rounded-md transition duration-300 ease-in-out focus:outline-none",
        {
          "text-white bg-blue-600 hover:bg-blue-700 focus:bg-blue-700": !variant || variant == "primary",
          "text-black bg-gray-100 hover:bg-gray-50 focus:bg-gray-50": variant == "white",
          "text-white bg-gray-950 hover:bg-gray-900 focus:bg-gray-900": variant == "black",
          "text-black bg-yellow-400 hover:bg-yellow-300 focus:bg-yellow-300": variant == "pro",
          "text-white bg-red-600 hover:bg-red-500 focus:bg-red-500": variant == "danger",
          "text-white bg-green-800 hover:bg-green-700 focus:bg-green-700": variant == "success",
          "bg-transparent": variant == "transparent",
          "w-full": fulled,
          "opacity-50 cursor-not-allowed": disabled
        },
        className
      )}
      {...props}
    >
      {children}
    </button>
  );
};
