// src/app/(user)/sign-up/page.tsx
"use client";

import { Button } from "#/lib/components/atoms/button";
import { Card } from "#/lib/components/atoms/card";
import { Checkbox } from "#/lib/components/atoms/checkbox/checkbox";
import { Input } from "#/lib/components/atoms/input";
import { Text } from "#/lib/components/atoms/text";
import Link from "next/link";
import type { ReactElement } from "react";

const SignInPage = (): ReactElement => {
  return (
    <>
      <Card size="sm">
        <div className="mb-2 p-0">
          <h1 className="mb-1 text-xl font-bold text-white md:text-2xl">Connect to your account</h1>
        </div>

        <div className="flex flex-col mt-2">
          <Input
            label="Email address"
            placeholder="john@company.com"
            type="email"
            className="mb-2"
          />

          <Input
            label="Password"
            placeholder="••••••••"
            type="password"
            className="mb-2.5"
          />

          <Input
            label="Confirm password"
            placeholder="••••••••"
            type="password"
            className="mb-2.5"
          />

          <Checkbox>
            I agree to the <Link className="text-blue-600 hover:text-blue-500" href="/terms-of-service">Terms of Service</Link>
          </Checkbox>

          <Button className="mt-2">Let&apos;s go</Button>

          <div className="flex flex-col mt-4">
            <Text className="text-gray-400">
            Already have an account ? <Link className="text-blue-600 hover:text-blue-500" href="/sign-in">Sign in</Link>
            </Text>
          </div>
        </div>
      </Card>
    </>
  );
};

export default SignInPage;

// src/routes/(auth)/(sign)/sign-up/+page.svelte
<script lang="ts">
  import { Input } from "$lib/components/input";

  let email: string;
  let password: string;
  let passwordConfirm: string;
</script>

<div class="p-6 space-y-4 md:space-y-6 sm:p-8">
  <h1 class="text-xl font-bold leading-tight tracking-tight md:text-2xl text-white">Create your account</h1>
  <form class="space-y-4 md:space-y-6" action="#">
      <div><Input type="email" bind:value={email} placeholder="johndoe@example.com" label="Email address" size="large" /></div>
      <div><Input type="password" bind:value={password} placeholder="••••••••" label="Choose a password" size="large" /></div>
      <div><Input type="password" bind:value={passwordConfirm} placeholder="••••••••" label="Confirm your password" size="large" /></div>
      <button type="button" class="px-3 py-2 w-full text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-1 focus:outline-none">Sign up</button>
      
      <p class="text-sm font-light text-gray-400">
        Already have an account? <a href="/sign-in" class="hover:text-gray-300 transition-all ease-in-out 2s">Log in</a>
      </p>
  </form>
</div>
